/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as UniAdminUniversityRouteImport } from './routes/uni-admin-university'
import { Route as UniAdminStatusRouteImport } from './routes/uni-admin-status'
import { Route as UniAdminReportsRouteImport } from './routes/uni-admin-reports'
import { Route as UniAdminProgrammesRouteImport } from './routes/uni-admin-programmes'
import { Route as UniAdminProgrammeAppsRouteImport } from './routes/uni-admin-programme-apps'
import { Route as UniAdminNotificationsRouteImport } from './routes/uni-admin-notifications'
import { Route as UniAdminFacultiesRouteImport } from './routes/uni-admin-faculties'
import { Route as UniAdminDocumentsRouteImport } from './routes/uni-admin-documents'
import { Route as UniAdminDashboardRouteImport } from './routes/uni-admin-dashboard'
import { Route as UniAdminBursariesRouteImport } from './routes/uni-admin-bursaries'
import { Route as UniAdminApplicationsRouteImport } from './routes/uni-admin-applications'
import { Route as UniAdminApplicationDetailsRouteImport } from './routes/uni-admin-application-details'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterSuccessRouteImport } from './routes/register-success'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProgrammeSearchRouteImport } from './routes/programme-search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ParentStudentProfileRouteImport } from './routes/parent-student-profile'
import { Route as ParentProgrammesRouteImport } from './routes/parent-programmes'
import { Route as ParentNotificationsRouteImport } from './routes/parent-notifications'
import { Route as ParentHelpRouteImport } from './routes/parent-help'
import { Route as ParentDeadlinesRouteImport } from './routes/parent-deadlines'
import { Route as ParentDashboardRouteImport } from './routes/parent-dashboard'
import { Route as ParentApplicationsRouteImport } from './routes/parent-applications'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobHubRouteImport } from './routes/job-hub'
import { Route as InterviewPracticeRouteImport } from './routes/interview-practice'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EmployerProfileRouteImport } from './routes/employer-profile'
import { Route as EmployerJobsRouteImport } from './routes/employer-jobs'
import { Route as EmployerDashboardRouteImport } from './routes/employer-dashboard'
import { Route as EmployerApplicantsRouteImport } from './routes/employer-applicants'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CounsellorReportsRouteImport } from './routes/counsellor-reports'
import { Route as CounsellorRecommendationsRouteImport } from './routes/counsellor-recommendations'
import { Route as CounsellorNotificationsRouteImport } from './routes/counsellor-notifications'
import { Route as CounsellorMissingDocsRouteImport } from './routes/counsellor-missing-docs'
import { Route as CounsellorLearnersRouteImport } from './routes/counsellor-learners'
import { Route as CounsellorLearnerProfileRouteImport } from './routes/counsellor-learner-profile'
import { Route as CounsellorDashboardRouteImport } from './routes/counsellor-dashboard'
import { Route as CounsellorCareerRouteImport } from './routes/counsellor-career'
import { Route as CounsellorApsResultsRouteImport } from './routes/counsellor-aps-results'
import { Route as CounsellorApplicationsRouteImport } from './routes/counsellor-applications'
import { Route as CareerGuidanceRouteImport } from './routes/career-guidance'
import { Route as BursariesRouteImport } from './routes/bursaries'
import { Route as BrowseUniversitiesRouteImport } from './routes/browse-universities'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ApplicationFormRouteImport } from './routes/application-form'
import { Route as ApplicationFeeRouteImport } from './routes/application-fee'
import { Route as AdminUsersRouteImport } from './routes/admin-users'
import { Route as AdminUniversitiesRouteImport } from './routes/admin-universities'
import { Route as AdminSettingsRouteImport } from './routes/admin-settings'
import { Route as AdminReportsRouteImport } from './routes/admin-reports'
import { Route as AdminProgrammesRouteImport } from './routes/admin-programmes'
import { Route as AdminNotificationsRouteImport } from './routes/admin-notifications'
import { Route as AdminJobsRouteImport } from './routes/admin-jobs'
import { Route as AdminFacultiesRouteImport } from './routes/admin-faculties'
import { Route as AdminEventsRouteImport } from './routes/admin-events'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AdminBursariesRouteImport } from './routes/admin-bursaries'
import { Route as AdminAuditLogsRouteImport } from './routes/admin-audit-logs'
import { Route as AdminApsRulesRouteImport } from './routes/admin-aps-rules'
import { Route as AdminApplicationsRouteImport } from './routes/admin-applications'
import { Route as AdminAccommodationsRouteImport } from './routes/admin-accommodations'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as AcademicResultsRouteImport } from './routes/academic-results'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationFeeSuccessRouteImport } from './routes/application-fee_.success'
import { Route as ApplicationFeeCancelRouteImport } from './routes/application-fee_.cancel'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminUniversityRoute = UniAdminUniversityRouteImport.update({
  id: '/uni-admin-university',
  path: '/uni-admin-university',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminStatusRoute = UniAdminStatusRouteImport.update({
  id: '/uni-admin-status',
  path: '/uni-admin-status',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminReportsRoute = UniAdminReportsRouteImport.update({
  id: '/uni-admin-reports',
  path: '/uni-admin-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminProgrammesRoute = UniAdminProgrammesRouteImport.update({
  id: '/uni-admin-programmes',
  path: '/uni-admin-programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminProgrammeAppsRoute = UniAdminProgrammeAppsRouteImport.update({
  id: '/uni-admin-programme-apps',
  path: '/uni-admin-programme-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminNotificationsRoute = UniAdminNotificationsRouteImport.update({
  id: '/uni-admin-notifications',
  path: '/uni-admin-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminFacultiesRoute = UniAdminFacultiesRouteImport.update({
  id: '/uni-admin-faculties',
  path: '/uni-admin-faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminDocumentsRoute = UniAdminDocumentsRouteImport.update({
  id: '/uni-admin-documents',
  path: '/uni-admin-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminDashboardRoute = UniAdminDashboardRouteImport.update({
  id: '/uni-admin-dashboard',
  path: '/uni-admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminBursariesRoute = UniAdminBursariesRouteImport.update({
  id: '/uni-admin-bursaries',
  path: '/uni-admin-bursaries',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminApplicationsRoute = UniAdminApplicationsRouteImport.update({
  id: '/uni-admin-applications',
  path: '/uni-admin-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const UniAdminApplicationDetailsRoute =
  UniAdminApplicationDetailsRouteImport.update({
    id: '/uni-admin-application-details',
    path: '/uni-admin-application-details',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/register-success',
  path: '/register-success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeSearchRoute = ProgrammeSearchRouteImport.update({
  id: '/programme-search',
  path: '/programme-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentStudentProfileRoute = ParentStudentProfileRouteImport.update({
  id: '/parent-student-profile',
  path: '/parent-student-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentProgrammesRoute = ParentProgrammesRouteImport.update({
  id: '/parent-programmes',
  path: '/parent-programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentNotificationsRoute = ParentNotificationsRouteImport.update({
  id: '/parent-notifications',
  path: '/parent-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentHelpRoute = ParentHelpRouteImport.update({
  id: '/parent-help',
  path: '/parent-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentDeadlinesRoute = ParentDeadlinesRouteImport.update({
  id: '/parent-deadlines',
  path: '/parent-deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent-dashboard',
  path: '/parent-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentApplicationsRoute = ParentApplicationsRouteImport.update({
  id: '/parent-applications',
  path: '/parent-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobHubRoute = JobHubRouteImport.update({
  id: '/job-hub',
  path: '/job-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewPracticeRoute = InterviewPracticeRouteImport.update({
  id: '/interview-practice',
  path: '/interview-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerProfileRoute = EmployerProfileRouteImport.update({
  id: '/employer-profile',
  path: '/employer-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsRoute = EmployerJobsRouteImport.update({
  id: '/employer-jobs',
  path: '/employer-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer-dashboard',
  path: '/employer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerApplicantsRoute = EmployerApplicantsRouteImport.update({
  id: '/employer-applicants',
  path: '/employer-applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorReportsRoute = CounsellorReportsRouteImport.update({
  id: '/counsellor-reports',
  path: '/counsellor-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorRecommendationsRoute =
  CounsellorRecommendationsRouteImport.update({
    id: '/counsellor-recommendations',
    path: '/counsellor-recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const CounsellorNotificationsRoute = CounsellorNotificationsRouteImport.update({
  id: '/counsellor-notifications',
  path: '/counsellor-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorMissingDocsRoute = CounsellorMissingDocsRouteImport.update({
  id: '/counsellor-missing-docs',
  path: '/counsellor-missing-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorLearnersRoute = CounsellorLearnersRouteImport.update({
  id: '/counsellor-learners',
  path: '/counsellor-learners',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorLearnerProfileRoute =
  CounsellorLearnerProfileRouteImport.update({
    id: '/counsellor-learner-profile',
    path: '/counsellor-learner-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const CounsellorDashboardRoute = CounsellorDashboardRouteImport.update({
  id: '/counsellor-dashboard',
  path: '/counsellor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorCareerRoute = CounsellorCareerRouteImport.update({
  id: '/counsellor-career',
  path: '/counsellor-career',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorApsResultsRoute = CounsellorApsResultsRouteImport.update({
  id: '/counsellor-aps-results',
  path: '/counsellor-aps-results',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorApplicationsRoute = CounsellorApplicationsRouteImport.update({
  id: '/counsellor-applications',
  path: '/counsellor-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerGuidanceRoute = CareerGuidanceRouteImport.update({
  id: '/career-guidance',
  path: '/career-guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const BursariesRoute = BursariesRouteImport.update({
  id: '/bursaries',
  path: '/bursaries',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseUniversitiesRoute = BrowseUniversitiesRouteImport.update({
  id: '/browse-universities',
  path: '/browse-universities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationFormRoute = ApplicationFormRouteImport.update({
  id: '/application-form',
  path: '/application-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationFeeRoute = ApplicationFeeRouteImport.update({
  id: '/application-fee',
  path: '/application-fee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUniversitiesRoute = AdminUniversitiesRouteImport.update({
  id: '/admin-universities',
  path: '/admin-universities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin-reports',
  path: '/admin-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgrammesRoute = AdminProgrammesRouteImport.update({
  id: '/admin-programmes',
  path: '/admin-programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin-notifications',
  path: '/admin-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin-jobs',
  path: '/admin-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/admin-faculties',
  path: '/admin-faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin-events',
  path: '/admin-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBursariesRoute = AdminBursariesRouteImport.update({
  id: '/admin-bursaries',
  path: '/admin-bursaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin-audit-logs',
  path: '/admin-audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApsRulesRoute = AdminApsRulesRouteImport.update({
  id: '/admin-aps-rules',
  path: '/admin-aps-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin-applications',
  path: '/admin-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccommodationsRoute = AdminAccommodationsRouteImport.update({
  id: '/admin-accommodations',
  path: '/admin-accommodations',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicResultsRoute = AcademicResultsRouteImport.update({
  id: '/academic-results',
  path: '/academic-results',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationFeeSuccessRoute = ApplicationFeeSuccessRouteImport.update({
  id: '/application-fee_/success',
  path: '/application-fee/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationFeeCancelRoute = ApplicationFeeCancelRouteImport.update({
  id: '/application-fee_/cancel',
  path: '/application-fee/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-results': typeof AcademicResultsRoute
  '/accommodation': typeof AccommodationRoute
  '/admin-accommodations': typeof AdminAccommodationsRoute
  '/admin-applications': typeof AdminApplicationsRoute
  '/admin-aps-rules': typeof AdminApsRulesRoute
  '/admin-audit-logs': typeof AdminAuditLogsRoute
  '/admin-bursaries': typeof AdminBursariesRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-events': typeof AdminEventsRoute
  '/admin-faculties': typeof AdminFacultiesRoute
  '/admin-jobs': typeof AdminJobsRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/admin-programmes': typeof AdminProgrammesRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-universities': typeof AdminUniversitiesRoute
  '/admin-users': typeof AdminUsersRoute
  '/application-fee': typeof ApplicationFeeRoute
  '/application-form': typeof ApplicationFormRoute
  '/applications': typeof ApplicationsRoute
  '/browse-universities': typeof BrowseUniversitiesRoute
  '/bursaries': typeof BursariesRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/counsellor-applications': typeof CounsellorApplicationsRoute
  '/counsellor-aps-results': typeof CounsellorApsResultsRoute
  '/counsellor-career': typeof CounsellorCareerRoute
  '/counsellor-dashboard': typeof CounsellorDashboardRoute
  '/counsellor-learner-profile': typeof CounsellorLearnerProfileRoute
  '/counsellor-learners': typeof CounsellorLearnersRoute
  '/counsellor-missing-docs': typeof CounsellorMissingDocsRoute
  '/counsellor-notifications': typeof CounsellorNotificationsRoute
  '/counsellor-recommendations': typeof CounsellorRecommendationsRoute
  '/counsellor-reports': typeof CounsellorReportsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/employer-applicants': typeof EmployerApplicantsRoute
  '/employer-dashboard': typeof EmployerDashboardRoute
  '/employer-jobs': typeof EmployerJobsRoute
  '/employer-profile': typeof EmployerProfileRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/interview-practice': typeof InterviewPracticeRoute
  '/job-hub': typeof JobHubRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/parent-applications': typeof ParentApplicationsRoute
  '/parent-dashboard': typeof ParentDashboardRoute
  '/parent-deadlines': typeof ParentDeadlinesRoute
  '/parent-help': typeof ParentHelpRoute
  '/parent-notifications': typeof ParentNotificationsRoute
  '/parent-programmes': typeof ParentProgrammesRoute
  '/parent-student-profile': typeof ParentStudentProfileRoute
  '/profile': typeof ProfileRoute
  '/programme-search': typeof ProgrammeSearchRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/settings': typeof SettingsRoute
  '/uni-admin-application-details': typeof UniAdminApplicationDetailsRoute
  '/uni-admin-applications': typeof UniAdminApplicationsRoute
  '/uni-admin-bursaries': typeof UniAdminBursariesRoute
  '/uni-admin-dashboard': typeof UniAdminDashboardRoute
  '/uni-admin-documents': typeof UniAdminDocumentsRoute
  '/uni-admin-faculties': typeof UniAdminFacultiesRoute
  '/uni-admin-notifications': typeof UniAdminNotificationsRoute
  '/uni-admin-programme-apps': typeof UniAdminProgrammeAppsRoute
  '/uni-admin-programmes': typeof UniAdminProgrammesRoute
  '/uni-admin-reports': typeof UniAdminReportsRoute
  '/uni-admin-status': typeof UniAdminStatusRoute
  '/uni-admin-university': typeof UniAdminUniversityRoute
  '/universities': typeof UniversitiesRoute
  '/application-fee/cancel': typeof ApplicationFeeCancelRoute
  '/application-fee/success': typeof ApplicationFeeSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-results': typeof AcademicResultsRoute
  '/accommodation': typeof AccommodationRoute
  '/admin-accommodations': typeof AdminAccommodationsRoute
  '/admin-applications': typeof AdminApplicationsRoute
  '/admin-aps-rules': typeof AdminApsRulesRoute
  '/admin-audit-logs': typeof AdminAuditLogsRoute
  '/admin-bursaries': typeof AdminBursariesRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-events': typeof AdminEventsRoute
  '/admin-faculties': typeof AdminFacultiesRoute
  '/admin-jobs': typeof AdminJobsRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/admin-programmes': typeof AdminProgrammesRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-universities': typeof AdminUniversitiesRoute
  '/admin-users': typeof AdminUsersRoute
  '/application-fee': typeof ApplicationFeeRoute
  '/application-form': typeof ApplicationFormRoute
  '/applications': typeof ApplicationsRoute
  '/browse-universities': typeof BrowseUniversitiesRoute
  '/bursaries': typeof BursariesRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/counsellor-applications': typeof CounsellorApplicationsRoute
  '/counsellor-aps-results': typeof CounsellorApsResultsRoute
  '/counsellor-career': typeof CounsellorCareerRoute
  '/counsellor-dashboard': typeof CounsellorDashboardRoute
  '/counsellor-learner-profile': typeof CounsellorLearnerProfileRoute
  '/counsellor-learners': typeof CounsellorLearnersRoute
  '/counsellor-missing-docs': typeof CounsellorMissingDocsRoute
  '/counsellor-notifications': typeof CounsellorNotificationsRoute
  '/counsellor-recommendations': typeof CounsellorRecommendationsRoute
  '/counsellor-reports': typeof CounsellorReportsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/employer-applicants': typeof EmployerApplicantsRoute
  '/employer-dashboard': typeof EmployerDashboardRoute
  '/employer-jobs': typeof EmployerJobsRoute
  '/employer-profile': typeof EmployerProfileRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/interview-practice': typeof InterviewPracticeRoute
  '/job-hub': typeof JobHubRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/parent-applications': typeof ParentApplicationsRoute
  '/parent-dashboard': typeof ParentDashboardRoute
  '/parent-deadlines': typeof ParentDeadlinesRoute
  '/parent-help': typeof ParentHelpRoute
  '/parent-notifications': typeof ParentNotificationsRoute
  '/parent-programmes': typeof ParentProgrammesRoute
  '/parent-student-profile': typeof ParentStudentProfileRoute
  '/profile': typeof ProfileRoute
  '/programme-search': typeof ProgrammeSearchRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/settings': typeof SettingsRoute
  '/uni-admin-application-details': typeof UniAdminApplicationDetailsRoute
  '/uni-admin-applications': typeof UniAdminApplicationsRoute
  '/uni-admin-bursaries': typeof UniAdminBursariesRoute
  '/uni-admin-dashboard': typeof UniAdminDashboardRoute
  '/uni-admin-documents': typeof UniAdminDocumentsRoute
  '/uni-admin-faculties': typeof UniAdminFacultiesRoute
  '/uni-admin-notifications': typeof UniAdminNotificationsRoute
  '/uni-admin-programme-apps': typeof UniAdminProgrammeAppsRoute
  '/uni-admin-programmes': typeof UniAdminProgrammesRoute
  '/uni-admin-reports': typeof UniAdminReportsRoute
  '/uni-admin-status': typeof UniAdminStatusRoute
  '/uni-admin-university': typeof UniAdminUniversityRoute
  '/universities': typeof UniversitiesRoute
  '/application-fee/cancel': typeof ApplicationFeeCancelRoute
  '/application-fee/success': typeof ApplicationFeeSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-results': typeof AcademicResultsRoute
  '/accommodation': typeof AccommodationRoute
  '/admin-accommodations': typeof AdminAccommodationsRoute
  '/admin-applications': typeof AdminApplicationsRoute
  '/admin-aps-rules': typeof AdminApsRulesRoute
  '/admin-audit-logs': typeof AdminAuditLogsRoute
  '/admin-bursaries': typeof AdminBursariesRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-events': typeof AdminEventsRoute
  '/admin-faculties': typeof AdminFacultiesRoute
  '/admin-jobs': typeof AdminJobsRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/admin-programmes': typeof AdminProgrammesRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-universities': typeof AdminUniversitiesRoute
  '/admin-users': typeof AdminUsersRoute
  '/application-fee': typeof ApplicationFeeRoute
  '/application-form': typeof ApplicationFormRoute
  '/applications': typeof ApplicationsRoute
  '/browse-universities': typeof BrowseUniversitiesRoute
  '/bursaries': typeof BursariesRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/counsellor-applications': typeof CounsellorApplicationsRoute
  '/counsellor-aps-results': typeof CounsellorApsResultsRoute
  '/counsellor-career': typeof CounsellorCareerRoute
  '/counsellor-dashboard': typeof CounsellorDashboardRoute
  '/counsellor-learner-profile': typeof CounsellorLearnerProfileRoute
  '/counsellor-learners': typeof CounsellorLearnersRoute
  '/counsellor-missing-docs': typeof CounsellorMissingDocsRoute
  '/counsellor-notifications': typeof CounsellorNotificationsRoute
  '/counsellor-recommendations': typeof CounsellorRecommendationsRoute
  '/counsellor-reports': typeof CounsellorReportsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/employer-applicants': typeof EmployerApplicantsRoute
  '/employer-dashboard': typeof EmployerDashboardRoute
  '/employer-jobs': typeof EmployerJobsRoute
  '/employer-profile': typeof EmployerProfileRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/interview-practice': typeof InterviewPracticeRoute
  '/job-hub': typeof JobHubRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/parent-applications': typeof ParentApplicationsRoute
  '/parent-dashboard': typeof ParentDashboardRoute
  '/parent-deadlines': typeof ParentDeadlinesRoute
  '/parent-help': typeof ParentHelpRoute
  '/parent-notifications': typeof ParentNotificationsRoute
  '/parent-programmes': typeof ParentProgrammesRoute
  '/parent-student-profile': typeof ParentStudentProfileRoute
  '/profile': typeof ProfileRoute
  '/programme-search': typeof ProgrammeSearchRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/settings': typeof SettingsRoute
  '/uni-admin-application-details': typeof UniAdminApplicationDetailsRoute
  '/uni-admin-applications': typeof UniAdminApplicationsRoute
  '/uni-admin-bursaries': typeof UniAdminBursariesRoute
  '/uni-admin-dashboard': typeof UniAdminDashboardRoute
  '/uni-admin-documents': typeof UniAdminDocumentsRoute
  '/uni-admin-faculties': typeof UniAdminFacultiesRoute
  '/uni-admin-notifications': typeof UniAdminNotificationsRoute
  '/uni-admin-programme-apps': typeof UniAdminProgrammeAppsRoute
  '/uni-admin-programmes': typeof UniAdminProgrammesRoute
  '/uni-admin-reports': typeof UniAdminReportsRoute
  '/uni-admin-status': typeof UniAdminStatusRoute
  '/uni-admin-university': typeof UniAdminUniversityRoute
  '/universities': typeof UniversitiesRoute
  '/application-fee_/cancel': typeof ApplicationFeeCancelRoute
  '/application-fee_/success': typeof ApplicationFeeSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic-results'
    | '/accommodation'
    | '/admin-accommodations'
    | '/admin-applications'
    | '/admin-aps-rules'
    | '/admin-audit-logs'
    | '/admin-bursaries'
    | '/admin-dashboard'
    | '/admin-events'
    | '/admin-faculties'
    | '/admin-jobs'
    | '/admin-notifications'
    | '/admin-programmes'
    | '/admin-reports'
    | '/admin-settings'
    | '/admin-universities'
    | '/admin-users'
    | '/application-fee'
    | '/application-form'
    | '/applications'
    | '/browse-universities'
    | '/bursaries'
    | '/career-guidance'
    | '/counsellor-applications'
    | '/counsellor-aps-results'
    | '/counsellor-career'
    | '/counsellor-dashboard'
    | '/counsellor-learner-profile'
    | '/counsellor-learners'
    | '/counsellor-missing-docs'
    | '/counsellor-notifications'
    | '/counsellor-recommendations'
    | '/counsellor-reports'
    | '/dashboard'
    | '/documents'
    | '/employer-applicants'
    | '/employer-dashboard'
    | '/employer-jobs'
    | '/employer-profile'
    | '/events'
    | '/help'
    | '/interview-practice'
    | '/job-hub'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/parent-applications'
    | '/parent-dashboard'
    | '/parent-deadlines'
    | '/parent-help'
    | '/parent-notifications'
    | '/parent-programmes'
    | '/parent-student-profile'
    | '/profile'
    | '/programme-search'
    | '/programs'
    | '/register'
    | '/register-success'
    | '/settings'
    | '/uni-admin-application-details'
    | '/uni-admin-applications'
    | '/uni-admin-bursaries'
    | '/uni-admin-dashboard'
    | '/uni-admin-documents'
    | '/uni-admin-faculties'
    | '/uni-admin-notifications'
    | '/uni-admin-programme-apps'
    | '/uni-admin-programmes'
    | '/uni-admin-reports'
    | '/uni-admin-status'
    | '/uni-admin-university'
    | '/universities'
    | '/application-fee/cancel'
    | '/application-fee/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic-results'
    | '/accommodation'
    | '/admin-accommodations'
    | '/admin-applications'
    | '/admin-aps-rules'
    | '/admin-audit-logs'
    | '/admin-bursaries'
    | '/admin-dashboard'
    | '/admin-events'
    | '/admin-faculties'
    | '/admin-jobs'
    | '/admin-notifications'
    | '/admin-programmes'
    | '/admin-reports'
    | '/admin-settings'
    | '/admin-universities'
    | '/admin-users'
    | '/application-fee'
    | '/application-form'
    | '/applications'
    | '/browse-universities'
    | '/bursaries'
    | '/career-guidance'
    | '/counsellor-applications'
    | '/counsellor-aps-results'
    | '/counsellor-career'
    | '/counsellor-dashboard'
    | '/counsellor-learner-profile'
    | '/counsellor-learners'
    | '/counsellor-missing-docs'
    | '/counsellor-notifications'
    | '/counsellor-recommendations'
    | '/counsellor-reports'
    | '/dashboard'
    | '/documents'
    | '/employer-applicants'
    | '/employer-dashboard'
    | '/employer-jobs'
    | '/employer-profile'
    | '/events'
    | '/help'
    | '/interview-practice'
    | '/job-hub'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/parent-applications'
    | '/parent-dashboard'
    | '/parent-deadlines'
    | '/parent-help'
    | '/parent-notifications'
    | '/parent-programmes'
    | '/parent-student-profile'
    | '/profile'
    | '/programme-search'
    | '/programs'
    | '/register'
    | '/register-success'
    | '/settings'
    | '/uni-admin-application-details'
    | '/uni-admin-applications'
    | '/uni-admin-bursaries'
    | '/uni-admin-dashboard'
    | '/uni-admin-documents'
    | '/uni-admin-faculties'
    | '/uni-admin-notifications'
    | '/uni-admin-programme-apps'
    | '/uni-admin-programmes'
    | '/uni-admin-reports'
    | '/uni-admin-status'
    | '/uni-admin-university'
    | '/universities'
    | '/application-fee/cancel'
    | '/application-fee/success'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic-results'
    | '/accommodation'
    | '/admin-accommodations'
    | '/admin-applications'
    | '/admin-aps-rules'
    | '/admin-audit-logs'
    | '/admin-bursaries'
    | '/admin-dashboard'
    | '/admin-events'
    | '/admin-faculties'
    | '/admin-jobs'
    | '/admin-notifications'
    | '/admin-programmes'
    | '/admin-reports'
    | '/admin-settings'
    | '/admin-universities'
    | '/admin-users'
    | '/application-fee'
    | '/application-form'
    | '/applications'
    | '/browse-universities'
    | '/bursaries'
    | '/career-guidance'
    | '/counsellor-applications'
    | '/counsellor-aps-results'
    | '/counsellor-career'
    | '/counsellor-dashboard'
    | '/counsellor-learner-profile'
    | '/counsellor-learners'
    | '/counsellor-missing-docs'
    | '/counsellor-notifications'
    | '/counsellor-recommendations'
    | '/counsellor-reports'
    | '/dashboard'
    | '/documents'
    | '/employer-applicants'
    | '/employer-dashboard'
    | '/employer-jobs'
    | '/employer-profile'
    | '/events'
    | '/help'
    | '/interview-practice'
    | '/job-hub'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/parent-applications'
    | '/parent-dashboard'
    | '/parent-deadlines'
    | '/parent-help'
    | '/parent-notifications'
    | '/parent-programmes'
    | '/parent-student-profile'
    | '/profile'
    | '/programme-search'
    | '/programs'
    | '/register'
    | '/register-success'
    | '/settings'
    | '/uni-admin-application-details'
    | '/uni-admin-applications'
    | '/uni-admin-bursaries'
    | '/uni-admin-dashboard'
    | '/uni-admin-documents'
    | '/uni-admin-faculties'
    | '/uni-admin-notifications'
    | '/uni-admin-programme-apps'
    | '/uni-admin-programmes'
    | '/uni-admin-reports'
    | '/uni-admin-status'
    | '/uni-admin-university'
    | '/universities'
    | '/application-fee_/cancel'
    | '/application-fee_/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicResultsRoute: typeof AcademicResultsRoute
  AccommodationRoute: typeof AccommodationRoute
  AdminAccommodationsRoute: typeof AdminAccommodationsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminApsRulesRoute: typeof AdminApsRulesRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBursariesRoute: typeof AdminBursariesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFacultiesRoute: typeof AdminFacultiesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProgrammesRoute: typeof AdminProgrammesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUniversitiesRoute: typeof AdminUniversitiesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApplicationFeeRoute: typeof ApplicationFeeRoute
  ApplicationFormRoute: typeof ApplicationFormRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BrowseUniversitiesRoute: typeof BrowseUniversitiesRoute
  BursariesRoute: typeof BursariesRoute
  CareerGuidanceRoute: typeof CareerGuidanceRoute
  CounsellorApplicationsRoute: typeof CounsellorApplicationsRoute
  CounsellorApsResultsRoute: typeof CounsellorApsResultsRoute
  CounsellorCareerRoute: typeof CounsellorCareerRoute
  CounsellorDashboardRoute: typeof CounsellorDashboardRoute
  CounsellorLearnerProfileRoute: typeof CounsellorLearnerProfileRoute
  CounsellorLearnersRoute: typeof CounsellorLearnersRoute
  CounsellorMissingDocsRoute: typeof CounsellorMissingDocsRoute
  CounsellorNotificationsRoute: typeof CounsellorNotificationsRoute
  CounsellorRecommendationsRoute: typeof CounsellorRecommendationsRoute
  CounsellorReportsRoute: typeof CounsellorReportsRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  EmployerApplicantsRoute: typeof EmployerApplicantsRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  EmployerJobsRoute: typeof EmployerJobsRoute
  EmployerProfileRoute: typeof EmployerProfileRoute
  EventsRoute: typeof EventsRoute
  HelpRoute: typeof HelpRoute
  InterviewPracticeRoute: typeof InterviewPracticeRoute
  JobHubRoute: typeof JobHubRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ParentApplicationsRoute: typeof ParentApplicationsRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentDeadlinesRoute: typeof ParentDeadlinesRoute
  ParentHelpRoute: typeof ParentHelpRoute
  ParentNotificationsRoute: typeof ParentNotificationsRoute
  ParentProgrammesRoute: typeof ParentProgrammesRoute
  ParentStudentProfileRoute: typeof ParentStudentProfileRoute
  ProfileRoute: typeof ProfileRoute
  ProgrammeSearchRoute: typeof ProgrammeSearchRoute
  ProgramsRoute: typeof ProgramsRoute
  RegisterRoute: typeof RegisterRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  SettingsRoute: typeof SettingsRoute
  UniAdminApplicationDetailsRoute: typeof UniAdminApplicationDetailsRoute
  UniAdminApplicationsRoute: typeof UniAdminApplicationsRoute
  UniAdminBursariesRoute: typeof UniAdminBursariesRoute
  UniAdminDashboardRoute: typeof UniAdminDashboardRoute
  UniAdminDocumentsRoute: typeof UniAdminDocumentsRoute
  UniAdminFacultiesRoute: typeof UniAdminFacultiesRoute
  UniAdminNotificationsRoute: typeof UniAdminNotificationsRoute
  UniAdminProgrammeAppsRoute: typeof UniAdminProgrammeAppsRoute
  UniAdminProgrammesRoute: typeof UniAdminProgrammesRoute
  UniAdminReportsRoute: typeof UniAdminReportsRoute
  UniAdminStatusRoute: typeof UniAdminStatusRoute
  UniAdminUniversityRoute: typeof UniAdminUniversityRoute
  UniversitiesRoute: typeof UniversitiesRoute
  ApplicationFeeCancelRoute: typeof ApplicationFeeCancelRoute
  ApplicationFeeSuccessRoute: typeof ApplicationFeeSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-university': {
      id: '/uni-admin-university'
      path: '/uni-admin-university'
      fullPath: '/uni-admin-university'
      preLoaderRoute: typeof UniAdminUniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-status': {
      id: '/uni-admin-status'
      path: '/uni-admin-status'
      fullPath: '/uni-admin-status'
      preLoaderRoute: typeof UniAdminStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-reports': {
      id: '/uni-admin-reports'
      path: '/uni-admin-reports'
      fullPath: '/uni-admin-reports'
      preLoaderRoute: typeof UniAdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-programmes': {
      id: '/uni-admin-programmes'
      path: '/uni-admin-programmes'
      fullPath: '/uni-admin-programmes'
      preLoaderRoute: typeof UniAdminProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-programme-apps': {
      id: '/uni-admin-programme-apps'
      path: '/uni-admin-programme-apps'
      fullPath: '/uni-admin-programme-apps'
      preLoaderRoute: typeof UniAdminProgrammeAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-notifications': {
      id: '/uni-admin-notifications'
      path: '/uni-admin-notifications'
      fullPath: '/uni-admin-notifications'
      preLoaderRoute: typeof UniAdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-faculties': {
      id: '/uni-admin-faculties'
      path: '/uni-admin-faculties'
      fullPath: '/uni-admin-faculties'
      preLoaderRoute: typeof UniAdminFacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-documents': {
      id: '/uni-admin-documents'
      path: '/uni-admin-documents'
      fullPath: '/uni-admin-documents'
      preLoaderRoute: typeof UniAdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-dashboard': {
      id: '/uni-admin-dashboard'
      path: '/uni-admin-dashboard'
      fullPath: '/uni-admin-dashboard'
      preLoaderRoute: typeof UniAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-bursaries': {
      id: '/uni-admin-bursaries'
      path: '/uni-admin-bursaries'
      fullPath: '/uni-admin-bursaries'
      preLoaderRoute: typeof UniAdminBursariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-applications': {
      id: '/uni-admin-applications'
      path: '/uni-admin-applications'
      fullPath: '/uni-admin-applications'
      preLoaderRoute: typeof UniAdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni-admin-application-details': {
      id: '/uni-admin-application-details'
      path: '/uni-admin-application-details'
      fullPath: '/uni-admin-application-details'
      preLoaderRoute: typeof UniAdminApplicationDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-success': {
      id: '/register-success'
      path: '/register-success'
      fullPath: '/register-success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme-search': {
      id: '/programme-search'
      path: '/programme-search'
      fullPath: '/programme-search'
      preLoaderRoute: typeof ProgrammeSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-student-profile': {
      id: '/parent-student-profile'
      path: '/parent-student-profile'
      fullPath: '/parent-student-profile'
      preLoaderRoute: typeof ParentStudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-programmes': {
      id: '/parent-programmes'
      path: '/parent-programmes'
      fullPath: '/parent-programmes'
      preLoaderRoute: typeof ParentProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-notifications': {
      id: '/parent-notifications'
      path: '/parent-notifications'
      fullPath: '/parent-notifications'
      preLoaderRoute: typeof ParentNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-help': {
      id: '/parent-help'
      path: '/parent-help'
      fullPath: '/parent-help'
      preLoaderRoute: typeof ParentHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-deadlines': {
      id: '/parent-deadlines'
      path: '/parent-deadlines'
      fullPath: '/parent-deadlines'
      preLoaderRoute: typeof ParentDeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-dashboard': {
      id: '/parent-dashboard'
      path: '/parent-dashboard'
      fullPath: '/parent-dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-applications': {
      id: '/parent-applications'
      path: '/parent-applications'
      fullPath: '/parent-applications'
      preLoaderRoute: typeof ParentApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-hub': {
      id: '/job-hub'
      path: '/job-hub'
      fullPath: '/job-hub'
      preLoaderRoute: typeof JobHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-practice': {
      id: '/interview-practice'
      path: '/interview-practice'
      fullPath: '/interview-practice'
      preLoaderRoute: typeof InterviewPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-profile': {
      id: '/employer-profile'
      path: '/employer-profile'
      fullPath: '/employer-profile'
      preLoaderRoute: typeof EmployerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-jobs': {
      id: '/employer-jobs'
      path: '/employer-jobs'
      fullPath: '/employer-jobs'
      preLoaderRoute: typeof EmployerJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-dashboard': {
      id: '/employer-dashboard'
      path: '/employer-dashboard'
      fullPath: '/employer-dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-applicants': {
      id: '/employer-applicants'
      path: '/employer-applicants'
      fullPath: '/employer-applicants'
      preLoaderRoute: typeof EmployerApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor-reports': {
      id: '/counsellor-reports'
      path: '/counsellor-reports'
      fullPath: '/counsellor-reports'
      preLoaderRoute: typeof CounsellorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor-recommendations': {
      id: '/counsellor-recommendations'
      path: '/counsellor-recommendations'
      fullPath: '/counsellor-recommendations'
      preLoaderRoute: typeof CounsellorRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor-notifications': {
      id: '/counsellor-notifications'
      path: '/counsellor-notifications'
      fullPath: '/counsellor-notifications'
      preLoaderRoute: typeof CounsellorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor-missing-docs': {
      id: '/counsellor-missing-docs'
      path: '/counsellor-missing-docs'
      fullPath: '/counsellor-missing-docs'
      preLoaderRoute: typeof CounsellorMissingDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor-learners': {
      id: '/counsellor-learners'
      path: '/counsellor-learners'
      fullPath: '/counsellor-learners'
      preLoaderRoute: typeof CounsellorLearnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor-learner-profile': {
      id: '/counsellor-learner-profile'
      path: '/counsellor-learner-profile'
      fullPath: '/counsellor-learner-profile'
      preLoaderRoute: typeof CounsellorLearnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor-dashboard': {
      id: '/counsellor-dashboard'
      path: '/counsellor-dashboard'
      fullPath: '/counsellor-dashboard'
      preLoaderRoute: typeof CounsellorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor-career': {
      id: '/counsellor-career'
      path: '/counsellor-career'
      fullPath: '/counsellor-career'
      preLoaderRoute: typeof CounsellorCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor-aps-results': {
      id: '/counsellor-aps-results'
      path: '/counsellor-aps-results'
      fullPath: '/counsellor-aps-results'
      preLoaderRoute: typeof CounsellorApsResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor-applications': {
      id: '/counsellor-applications'
      path: '/counsellor-applications'
      fullPath: '/counsellor-applications'
      preLoaderRoute: typeof CounsellorApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-guidance': {
      id: '/career-guidance'
      path: '/career-guidance'
      fullPath: '/career-guidance'
      preLoaderRoute: typeof CareerGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bursaries': {
      id: '/bursaries'
      path: '/bursaries'
      fullPath: '/bursaries'
      preLoaderRoute: typeof BursariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse-universities': {
      id: '/browse-universities'
      path: '/browse-universities'
      fullPath: '/browse-universities'
      preLoaderRoute: typeof BrowseUniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-form': {
      id: '/application-form'
      path: '/application-form'
      fullPath: '/application-form'
      preLoaderRoute: typeof ApplicationFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-fee': {
      id: '/application-fee'
      path: '/application-fee'
      fullPath: '/application-fee'
      preLoaderRoute: typeof ApplicationFeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users': {
      id: '/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-universities': {
      id: '/admin-universities'
      path: '/admin-universities'
      fullPath: '/admin-universities'
      preLoaderRoute: typeof AdminUniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-settings': {
      id: '/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reports': {
      id: '/admin-reports'
      path: '/admin-reports'
      fullPath: '/admin-reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-programmes': {
      id: '/admin-programmes'
      path: '/admin-programmes'
      fullPath: '/admin-programmes'
      preLoaderRoute: typeof AdminProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-notifications': {
      id: '/admin-notifications'
      path: '/admin-notifications'
      fullPath: '/admin-notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-jobs': {
      id: '/admin-jobs'
      path: '/admin-jobs'
      fullPath: '/admin-jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-faculties': {
      id: '/admin-faculties'
      path: '/admin-faculties'
      fullPath: '/admin-faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-events': {
      id: '/admin-events'
      path: '/admin-events'
      fullPath: '/admin-events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-bursaries': {
      id: '/admin-bursaries'
      path: '/admin-bursaries'
      fullPath: '/admin-bursaries'
      preLoaderRoute: typeof AdminBursariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-audit-logs': {
      id: '/admin-audit-logs'
      path: '/admin-audit-logs'
      fullPath: '/admin-audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-aps-rules': {
      id: '/admin-aps-rules'
      path: '/admin-aps-rules'
      fullPath: '/admin-aps-rules'
      preLoaderRoute: typeof AdminApsRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-applications': {
      id: '/admin-applications'
      path: '/admin-applications'
      fullPath: '/admin-applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-accommodations': {
      id: '/admin-accommodations'
      path: '/admin-accommodations'
      fullPath: '/admin-accommodations'
      preLoaderRoute: typeof AdminAccommodationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-results': {
      id: '/academic-results'
      path: '/academic-results'
      fullPath: '/academic-results'
      preLoaderRoute: typeof AcademicResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-fee_/success': {
      id: '/application-fee_/success'
      path: '/application-fee/success'
      fullPath: '/application-fee/success'
      preLoaderRoute: typeof ApplicationFeeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-fee_/cancel': {
      id: '/application-fee_/cancel'
      path: '/application-fee/cancel'
      fullPath: '/application-fee/cancel'
      preLoaderRoute: typeof ApplicationFeeCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicResultsRoute: AcademicResultsRoute,
  AccommodationRoute: AccommodationRoute,
  AdminAccommodationsRoute: AdminAccommodationsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminApsRulesRoute: AdminApsRulesRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBursariesRoute: AdminBursariesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFacultiesRoute: AdminFacultiesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProgrammesRoute: AdminProgrammesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUniversitiesRoute: AdminUniversitiesRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApplicationFeeRoute: ApplicationFeeRoute,
  ApplicationFormRoute: ApplicationFormRoute,
  ApplicationsRoute: ApplicationsRoute,
  BrowseUniversitiesRoute: BrowseUniversitiesRoute,
  BursariesRoute: BursariesRoute,
  CareerGuidanceRoute: CareerGuidanceRoute,
  CounsellorApplicationsRoute: CounsellorApplicationsRoute,
  CounsellorApsResultsRoute: CounsellorApsResultsRoute,
  CounsellorCareerRoute: CounsellorCareerRoute,
  CounsellorDashboardRoute: CounsellorDashboardRoute,
  CounsellorLearnerProfileRoute: CounsellorLearnerProfileRoute,
  CounsellorLearnersRoute: CounsellorLearnersRoute,
  CounsellorMissingDocsRoute: CounsellorMissingDocsRoute,
  CounsellorNotificationsRoute: CounsellorNotificationsRoute,
  CounsellorRecommendationsRoute: CounsellorRecommendationsRoute,
  CounsellorReportsRoute: CounsellorReportsRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  EmployerApplicantsRoute: EmployerApplicantsRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
  EmployerJobsRoute: EmployerJobsRoute,
  EmployerProfileRoute: EmployerProfileRoute,
  EventsRoute: EventsRoute,
  HelpRoute: HelpRoute,
  InterviewPracticeRoute: InterviewPracticeRoute,
  JobHubRoute: JobHubRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ParentApplicationsRoute: ParentApplicationsRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  ParentDeadlinesRoute: ParentDeadlinesRoute,
  ParentHelpRoute: ParentHelpRoute,
  ParentNotificationsRoute: ParentNotificationsRoute,
  ParentProgrammesRoute: ParentProgrammesRoute,
  ParentStudentProfileRoute: ParentStudentProfileRoute,
  ProfileRoute: ProfileRoute,
  ProgrammeSearchRoute: ProgrammeSearchRoute,
  ProgramsRoute: ProgramsRoute,
  RegisterRoute: RegisterRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  SettingsRoute: SettingsRoute,
  UniAdminApplicationDetailsRoute: UniAdminApplicationDetailsRoute,
  UniAdminApplicationsRoute: UniAdminApplicationsRoute,
  UniAdminBursariesRoute: UniAdminBursariesRoute,
  UniAdminDashboardRoute: UniAdminDashboardRoute,
  UniAdminDocumentsRoute: UniAdminDocumentsRoute,
  UniAdminFacultiesRoute: UniAdminFacultiesRoute,
  UniAdminNotificationsRoute: UniAdminNotificationsRoute,
  UniAdminProgrammeAppsRoute: UniAdminProgrammeAppsRoute,
  UniAdminProgrammesRoute: UniAdminProgrammesRoute,
  UniAdminReportsRoute: UniAdminReportsRoute,
  UniAdminStatusRoute: UniAdminStatusRoute,
  UniAdminUniversityRoute: UniAdminUniversityRoute,
  UniversitiesRoute: UniversitiesRoute,
  ApplicationFeeCancelRoute: ApplicationFeeCancelRoute,
  ApplicationFeeSuccessRoute: ApplicationFeeSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
